/**
 * ES module generation utilities
 * @fileoverview Generates final ES module code from processing results
 * @author Peter Naydenov
 * @version 1.0.0
 */

import { debug } from '../utils/logger.js';

/**
 * Generate ES module code from processing result
 * @param {import('./types/processing.js').ProcessingResult} result - Processing result
 * @param {import('./types/plugin.js').MorphPluginOptions} options - Plugin options
 * @returns {string} Generated ES module code
 */
export function generateESModule(result, options) {
  const parts = [];

  // Add file header comment
  parts.push(
    `// Generated by vite-plugin-morph from ${result.metadata?.filePath || 'unknown'}`
  );
  parts.push(`// Generated at: ${new Date().toISOString()}`);
  parts.push(`// Processing time: ${result.metadata?.processingTime || 0}ms`);
  parts.push('');

  // Add CSS exports if present
  if (result.cssExports && Object.keys(result.cssExports).length > 0) {
    parts.push('// CSS module exports');
    parts.push(
      `export const styles = ${JSON.stringify(result.cssExports, null, 2)};`
    );
    parts.push('');
  }

  // Add handshake in development mode
  if (result.metadata?.components?.handshake && !isProductionMode(options)) {
    parts.push('// Handshake data (development only)');
    parts.push(
      `export const handshake = ${JSON.stringify(result.handshakeData, null, 2)};`
    );
    parts.push('');
  }

  // Add render function export
  if (result.renderFunction) {
    parts.push('// Render function');
    parts.push('export default ' + result.renderFunction.toString() + ';');
  } else {
    parts.push('// No render function (CSS-only file)');
  }

  // Add source map reference if enabled
  if (options.development?.sourceMaps && result.map) {
    parts.push('');
    parts.push('//# sourceMappingURL=' + result.map.file);
  }

  return parts.join('\n');
}

/**
 * Generate CSS-only module code
 * @param {Record<string,string>} cssExports - CSS exports
 * @param {import('./types/plugin.js').MorphPluginOptions} options - Plugin options
 * @returns {string} Generated ES module code
 */
export function generateCSSOnlyModule(cssExports, options) {
  const parts = [];

  // Add file header comment
  parts.push(`// Generated by vite-plugin-morph (CSS-only module)`);
  parts.push(`// Generated at: ${new Date().toISOString()}`);
  parts.push('');

  // Add CSS exports
  parts.push('// CSS module exports');
  parts.push(`export const styles = ${JSON.stringify(cssExports, null, 2)};`);
  parts.push('');

  // Add source map reference if enabled
  if (options.development?.sourceMaps) {
    parts.push('');
    parts.push('//# sourceMappingURL=styles.js.map');
  }

  return parts.join('\n');
}

/**
 * Check if running in production mode
 * @param {import('./types/plugin.js').MorphPluginOptions} options - Plugin options
 * @returns {boolean} Whether in production mode
 */
function isProductionMode(options) {
  return (
    process.env.NODE_ENV === 'production' ||
    process.argv.includes('--production') ||
    options.production?.removeHandshake === true
  );
}

/**
 * Validate generated module code
 * @param {string} code - Generated code
 * @returns {boolean} Whether code is valid
 */
export function validateGeneratedCode(code) {
  try {
    // Basic syntax check
    new Function(code);
    return true;
  } catch (error) {
    debug(`Generated code validation failed: ${error.message}`);
    return false;
  }
}

/**
 * Create module metadata
 * @param {import('./types/processing.js').ProcessingResult} result - Processing result
 * @returns {Object} Module metadata
 */
export function createModuleMetadata(result) {
  return {
    type: result.isCSSOnly ? 'css-module' : 'morph-component',
    hasCSS: !!result.cssExports,
    hasTemplate: !!result.renderFunction,
    hasHandshake: !!result.handshakeData,
    processingTime: result.metadata?.processingTime || 0,
    fileSize: Buffer.byteLength(result.code || '', 'utf8'),
    generatedAt: new Date().toISOString(),
  };
}
